name = "webhook-emitter-cf-workers"
type = "javascript"
routes = ["https://vcrypto-webhook-emitter.sumidora.com"]
workers_dev = false
[vars]
USER_AGENT = "webhook-emitter-cf-workers/0.1 (+https://github.com/virtualCrypto-discord/webhook-emitter-cf-workers)"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
